[target.xtensa-esp32-none-elf]
runner = "espflash flash -B 921600 --monitor -p /dev/ttyUSB0"


[env]
ESP_LOGLEVEL="INFO"
[build]
rustflags = [
  
  "-C", "link-arg=-Tlinkall.x",

  "-C", "link-arg=-Trom_functions.x",

  "-C", "link-arg=-Tdefmt.x",

  "-C", "force-frame-pointers",

  "-C", "link-arg=-nostartfiles",
  
]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["alloc", "core"] # 
